LPS-190069
wanderlast/liferay-portal pull request #105
Opened 2023-08-17 08:13 UTC by locpham97

Hi @wanderlast ,
https://liferay.atlassian.net/browse/LPS-190069
Please help me review this PR.
I also updated the Vatican country follow your guidance and revert the countries's idd in the Caribbean Region.
If I missed from your ideas, feel free to comment it in here.
I am looking forward to hearing your response
Many thanks,
Loc

2023-08-17 08:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-17 22:48 UTC, wanderlast commented
Hi @locpham97, please see the comments I've left on this and let me know if any need further explanation. Thanks!

2023-08-18 03:21 UTC, locpham97 commented
Hi @wanderlast ,
Thanks for replying to me.
Could you check it and mention any missing information in here?
Many thanks.

2023-08-18 03:29 UTC, wanderlast requested changes

2023-08-18 03:29 UTC, wanderlast commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/countries.json
> +		"name": "vatican-city",
Missing IDD, it should be "39" similar to how it was prior to the changes you made.

2023-08-18 03:29 UTC, wanderlast commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/countries.json
> +		"name": "bonaire-sint-eustatius-saba",
I'm marking this as an example, but this applies to all "name" changes. 

The "Name" seen here is actually meant to be a key listed in portal-language-lang's Language.properties file. For example, you can search and find "country.bonaire-st-eustatius-saba". Therefore, if you want to make changes to the listed names of the countries, you cannot do it in this file, you must do it in the Language.properties and Language_en.properties files. Please make changes in those files if any names need to be changed.

2023-08-18 03:29 UTC, wanderlast commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/countries.json
> +		"idd": "44-1481",
While an IDD can have both the country code and an area code, we only need the country code in our case. Despite being labeled as "IDD," it's listed as "Country Calling Code" on the Country Management screen so the area code is not necessary. This also applies to the Isle of Man and possibly other entries, so please take a look if you get a chance and remove those. Thanks!

2023-08-18 03:29 UTC, wanderlast commented
Hi @locpham97,

Sorry about that, forgot to finalize it. Can you see the three comments I've left?

2023-08-18 03:31 UTC, locpham97 commented
Hi @wanderlast ,
Thanks for leaving the comments.
I will fix it now.

2023-08-18 03:35 UTC, locpham97 commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/countries.json
> +		"name": "bonaire-sint-eustatius-saba",
the responsibility for the task is updated again about regions and countries json.  I will revert it but I do not update the language.properties

2023-08-18 04:41 UTC, locpham97 commented
Hi @wanderlast ,
I updated it.

2023-08-18 06:44 UTC, locpham97 commented
Hi @wanderlast ,
Next week, 
I am on vacation. If you could leave the comments here or continue the LPS.
Many thanks,
Loc

2023-08-19 03:09 UTC, wanderlast commented
This LGTM.

2023-08-28 03:40 UTC, locpham97 commented
Hey @wanderlast ,
Could you help me to forward this PR?
Thanks,
Loc

2023-09-11 05:01 UTC, locpham97 commented
Hi @wanderlast ,
 Any update for this PR?
I'd appreciate it if you any feedback or updates.
Thanks,
Loc

2023-09-12 00:34 UTC, wanderlast commented
Hi @locpham97,
I'm currently waiting on feedback from the GS team on the client's requirements. I'll let you know once I hear back from them.

2023-10-09 07:28 UTC, locpham97 commented
Hi @wanderlast ,
Any update for this PR?
I'd appreciate it if you any feedback or updates.
Thanks,
Loc

2023-10-10 03:32 UTC, wanderlast commented
Hi @locpham97,

Since you're not changing names or adding other parameters, I think we should omit the changes to Macau and Hong Kong here. We can readd them in the LPS that adds the actual system setting since we don't want to change the default behavior for clients without alerting them.

So please do the following:
1. Remove the notes about "(see also separate country code entry under X)" for Taiwan, Macao and Hong Kong
2. Remove the country listings for Macao and Hong Kong (Taiwan is already there and can stay)

If you need help explaining this to the client/GS, please let me know. Otherwise this looks good to me. Thanks!

2023-10-13 07:00 UTC, ces-locpham commented
HI @wanderlast , 
I will update this PR. Could you help me forward this PR?
Many thanks,
Loc

2023-10-13 07:13 UTC, locpham97 commented
I updated it

2023-10-14 01:42 UTC, wanderlast approved these changes

2023-10-16 10:27 UTC, locpham97 commented
Hi @wanderlast , 
I want to ask more for this ticket. Should the next plan for the ticket  be sent to the product team?

2023-10-17 02:36 UTC, wanderlast commented
@locpham97 yes, I'll be forwarding it to the product team

2023-10-18 03:36 UTC, locpham97 commented
@wanderlast Thanks so much

2023-10-20 03:08 UTC, locpham97 commented
Hi @wanderlast,

Could you please send me the PR that you forwarded to the product team? I'd like to track it for convenience.

2023-10-24 21:41 UTC, wanderlast commented
Forwarded it to: https://github.com/liferay-commerce/liferay-portal/pull/4359

2023-10-24 21:41 UTC, closed without merging